### ISSUE TITLE
Support for Reusable blocks

### ISSUE THREAD

**Issue by williamjulianvicary** [wpengine/wp-graphql-content-blocks#103]
I noticed that #54 was closed as resolved for the Classic Editor component of the issue but the reusable block item is still problematic.

I can see we can query like so:
```gql
query GetPageData {
  pageBy(uri: "/test-uri") {
    editorBlocks(flat: true) {
      blockEditorCategoryName
      name
      ... on CoreBlock {
        attributes {
          ref
        }
      }
    }
  }
}
```

This identifies the block type as reusable, and we're able to retrieve the ref attribute associated with the reusable block, however as far as I can tell it's not then possible to query for the reusable block directly. We're also using Faust, which means ideally we'll be wanting to pass down the complete response rather than having to resolve the appropriate block within the CoreBlock.

We can get the innerHtml but that doesn't allow us to then handle the attribute, and I see that blockJSON was removed with the release of wp-graphql-content-blocks which would have been the other option, possibly.

```json
{
    "pageBy": {
      "editorBlocks": [
        {
          "blockEditorCategoryName": "reusable",
          "name": "core/block",
          "attributes": {
            "ref": 2575,
            "lock": null
          }
        }
      ]
    }
  }
```

I guess ideally these blocks would be resolved to the underlying blocks (as flattened innerBlocks?) within the response, at which point they'd then be usable as if they were any other block.

This is a bit of a blocker for us using Faust long term for clients, the utility of reusable blocks is unsurpassed for repetitive content that needs to be centrally maintained and the alternative is either - produce static non-editable blocks or ask our clients to put up with copy + paste across all of their Gutenberg pages - neither a great option!

Is this on the roadmap?

**Comment by williamjulianvicary** [comment]
Looks like this could be quite a trivial solution, add the below code to [ContentBlocksResolver.php:56](https://github.com/wpengine/wp-graphql-content-blocks/blob/main/includes/Data/ContentBlocksResolver.php#L56) and the reusable blocks resolve as anticipated:

Note: This only 

```
        // Resolve reusable blocks
        $new_parsed_blocks = [];
        foreach ($parsed_blocks as $block) {
            if ($block['blockName'] === 'core/block' && $block['attrs']['ref']) {
                $reusable_blocks = parse_blocks( get_post( $block['attrs']['ref'] )->post_content );
                if (!empty($reusable_blocks)) {
                    $new_parsed_blocks += $reusable_blocks;
                }
            } else {
                $new_parsed_blocks[] = $block;
            }
        }

        $parsed_blocks = $new_parsed_blocks;
```

**Comment by theodesp** [comment]
@williamjulianvicary Thanks. Sure go ahead. We will review the code with the team.

**Comment by theodesp** [comment]
@williamjulianvicary

We do require a one time CLA for people adding contributions:

If you could review and fill in this form: 

https://docs.google.com/forms/d/1O5bQCRHSSJmrOCAzWYJBIHjBNnVRg2PboSvuB2NfAI4/edit

Then we will send you a DocuSign to complete.

Then we can review your PRs.

Thank you.

**Comment by williamjulianvicary** [comment]
That's complete - let me know if you have any questions

**Comment by theodesp** [comment]
Merged https://github.com/wpengine/wp-graphql-content-blocks/pull/104
