### ISSUE TITLE
ACF Blocks data is not displaying

### ISSUE THREAD

**Issue by sunilsingh2019** [wpengine/wp-graphql-content-blocks#107]
I am attempting to query ACF blocks, but it seems that the data from the blocks is not being displayed. Could you please assist me with this?
![image](https://github.com/wpengine/wp-graphql-content-blocks/assets/26164995/6157d461-27f7-49ce-bab7-c14e5e8be01a)

**Comment by theodesp** [comment]
Hey @sunilsingh2019 It looks like the page contents are empty there. Could you please post the contents of the database there? You can find that using Adminer tool:

<img width="1114" alt="Screenshot 2023-05-26 at 10 48 29" src="https://github.com/wpengine/wp-graphql-content-blocks/assets/328805/cb132585-9000-4626-b0f2-edae2aed55f3">

**Comment by sunilsingh2019** [comment]
Hello @theodesp, the content is not empty as the database is full of content. However, I am experiencing an issue with the query for ACF blocks not showing up, while it's working fine for core blocks.
<img width="1130" alt="Screen Shot 2023-05-30 at 9 51 33 am" src="https://github.com/wpengine/wp-graphql-content-blocks/assets/26164995/44c5c510-cb56-43e7-8c19-71cf0139bd5a">
