### ISSUE TITLE
Plugin breaks GraphQL schema if CPT slug contains dash (`-`)

### ISSUE THREAD

**Issue by szaleq** [wpengine/wp-graphql-content-blocks#108]
Some interface type names are invalid. 
For example, I have a `case-study` CPT registered. This causes `wp-graphql-content-blocks` to create an interface named `NodeWithCase-studyEditorBlock`, which is invalid in GraphQL and causes errors. `GraphiQL` doesn't load, it presents the error in the console: `Uncaught (in promise) GraphQLError: Names must only contain [_a-zA-Z0-9] but "NodeWithCase-studyEditorBlocks" does not.`
![obraz](https://github.com/wpengine/wp-graphql-content-blocks/assets/25011639/c257b019-f338-43c2-965e-de4d6b49d169)

I believe the code responsible for this is in `WPGraphQL\ContentBlocks\Type\InterfaceType\PostTypeBlockInterface` class, [here](https://github.com/wpengine/wp-graphql-content-blocks/blob/5765443e4a95698622cf54f21cb010a81b1ab868/includes/Type/InterfaceType/PostTypeBlockInterface.php#L25) and [here](https://github.com/wpengine/wp-graphql-content-blocks/blob/5765443e4a95698622cf54f21cb010a81b1ab868/includes/Type/InterfaceType/PostTypeBlockInterface.php#L46). This code uses `ucfirst` on `$post_type`, which is a post slug containing a dash. I think it should rather use `Utils::format_type_name`, like [here in the `Registry` class](https://github.com/wpengine/wp-graphql-content-blocks/blob/5765443e4a95698622cf54f21cb010a81b1ab868/includes/Registry/Registry.php#L192).

**Comment by theodesp** [comment]
@szaleq this is already fixed and we will be publishing a new Release today.
