### ISSUE TITLE
Add support for genesis-custom-blocks

### ISSUE THREAD

**Issue by Muzammil-khan710** [wpengine/wp-graphql-content-blocks#112]
## Bug summary

When querying data with graphql , fields are coming empty. It should output the data of fields .

## Steps to reproduce

1. Create a genesis custom block .
2. Add custom block to a page/post .
3. Open grapgql IDE on wordpress .

## Expected behavior

should output the data of fields present in the custom block

## Actual behavior

The fields are coming empty also no errors.

## Versions

 - WordPress version: 6.2.2
 - wpgraphql version: 1.14.3
 - WPGraphQL Content Blocks version: 0.2.1
 - Genesis Custom Blocks version: 1.5.1
![Screenshot (306)](https://github.com/wpengine/wp-graphql-content-blocks/assets/82377076/548b46e6-6329-4420-a251-1da849f10b81)

**Comment by theodesp** [comment]
Hey @Muzammil-khan710 . I just checked out the free plugin

https://www.studiopress.com/genesis-custom-blocks/

and used the  default example block that contains a form:

<img width="1065" alt="Screenshot 2023-06-12 at 11 02 39" src="https://github.com/wpengine/wp-graphql-content-blocks/assets/328805/9e5647ac-3513-4dc0-8a25-dbb33ef7e216">

And I was able to query the attributes of that block:
<img width="1548" alt="Screenshot 2023-06-12 at 11 05 09" src="https://github.com/wpengine/wp-graphql-content-blocks/assets/328805/d055abbe-8532-438f-ac48-2112fdc32c01">


Would you mind posting the contents of the post as stored in the database? For example here is the one using Adminer:

<img width="1275" alt="Screenshot 2023-06-12 at 11 04 03" src="https://github.com/wpengine/wp-graphql-content-blocks/assets/328805/7a06ebf1-6969-472c-9b15-344c42b011cb">

It would also help if you post the Attributes docs for the custom GenesisCustomBlocksTest block that you have as shown in my screenshot.

**Comment by theodesp** [comment]
Also could you check the latest version of the plugin v0.3.0?

**Comment by Muzammil-khan710** [comment]
Hey @theodesp , I have just updated the plugin to v0.3.0 and now data of fields are coming as expected .
I am using hosted(live) Wordpress instead of locally installed. 
Also I have created and added custom block to one page and now when I am querying, the first field is coming as null yet there is only one component and the attributes are coming in two objects .
![Screenshot (313)](https://github.com/wpengine/wp-graphql-content-blocks/assets/82377076/1bcccc28-7a59-42da-a9be-02d02c8f33a2)
![Screenshot (314)](https://github.com/wpengine/wp-graphql-content-blocks/assets/82377076/d929bba5-91d1-4353-a0c6-9e4657c92713)

**Comment by theodesp** [comment]
Could you post the content of the database post as a minimal reproducible example? I will try to create a similar block and verify. Thank you.

**Comment by Muzammil-khan710** [comment]
Here's what I found.

**Comment by Muzammil-khan710** [comment]
Here's what I found

**Comment by theodesp** [comment]
@Muzammil-khan710 thats strange. I cannot reproduce here:

<img width="807" alt="Screenshot 2023-06-13 at 15 38 15" src="https://github.com/wpengine/wp-graphql-content-blocks/assets/328805/fc1d3d94-fffb-488b-ba68-51693582a018">
<img width="1216" alt="Screenshot 2023-06-13 at 15 38 06" src="https://github.com/wpengine/wp-graphql-content-blocks/assets/328805/76faead2-908f-44f4-9f7e-d66b0d5602e6">

Is something that we are missing?

**Comment by Muzammil-khan710** [comment]
Yes, @theodesp . I will try re-installing every plugin and try again may be there's some sort of bug while querying. Might be there's some version problem of a plugin . That's why it is behaving like this.
Will let you know .
Thanks .

**Comment by Muzammil-khan710** [comment]
Hey @theodesp , I have re-installed all plugins and now it's working as expected. Thank you !

**Comment by Muzammil-khan710** [comment]
## Bug summary

Hey @theodesp , I am using `Nextjs` and `Wordpress`  as headless. I am using `WPGraphQL Content Blocks` and I have created a custom block using `genesis-custom-blocks`. Now when I am querying the data locally it is coming as expected and I can find every field as it should. Let's say I am getting all the data for every block paragraph, headings etc. same for the custom block and I can even style them based on attributes coming from the field. My problem is my `custom-block-component` is going under `fallbackBlock` provided by `WordPressBlocksViewer`  Also my custom-block-component appears as it should on initial render for just few ms  than it goes in the fallbackBlock  on my hosted website. But it is working fine when I am using my app in locally. 

## Steps to reproduce

1. Create a genesis custom block .
2. Add custom block to a page/post .
3. Open grapgql IDE on wordpress .
4. Create a new Nextjs project and follow this [guide](https://faustjs.org/docs/getting-started).

## Expected behavior

It should output the attributes along with renderedHtml of custom block in live/hosted website. 
## Actual behavior

Currently attributes of custom block are coming when we are running app locally but it should also come when we are using hosted website. All other blocks are coming as they expected ex: headings, paragraphs, images...

## Versions

 - WordPress version: 6.2.2
 - Wpgraphql version: 1.14.4
 - WPGraphQL Content Blocks version: 0.3.0
 - Genesis Custom Blocks version: 1.5.1
 - NextJs version: 13.1.5
 - React version: 18.2.0
 - apollo/client version: 3.7.14
 -  faustwp/blocks version:  0.3.1
 -  faustwp/cli :  0.2.12
 -  faustwp/core:  0.2.11
 
 
 ### Query
![Screenshot (325)](https://github.com/wpengine/wp-graphql-content-blocks/assets/82377076/f70fa184-1bac-4d38-9109-8b5391e15dbc)

### Live website
![Screenshot (329)](https://github.com/wpengine/wp-graphql-content-blocks/assets/82377076/5269aaa3-94ce-4741-8622-07cd5892867f)

### Localhost
![Screenshot (330)](https://github.com/wpengine/wp-graphql-content-blocks/assets/82377076/2ee155b6-a90d-457e-abbe-ef2417b21968)

**Comment by Muzammil-khan710** [comment]
Hey @theodesp, I have done changes that you have mentioned but I am still getting the same problem.


https://github.com/wpengine/wp-graphql-content-blocks/assets/82377076/dee25121-0a9c-4bc0-8d17-8822b4c98793



live url -> https://rovae-website-git-headlessmk-chintankamani.vercel.app/blog/the-importance-of-user-centered-design#conclusion

**Comment by theodesp** [comment]
Hey @Muzammil-khan710 I don't see the displayName or the config.name in the exported component:

<img width="1220" alt="Screenshot 2023-06-19 at 13 46 42" src="https://github.com/wpengine/wp-graphql-content-blocks/assets/328805/4d657a1f-5805-4d26-88fc-2452294249e8">
I can see them in the rest of the components:

`CoreParagraph`, `CoreHeading` and so on have it but not in `GenesisCustomBlocksComponent` as you can see in the picture.

This means that it will render the fallback block.

Please make sure you verify all your components contains either the `displayName` or the `config.name` properties.

**Comment by theodesp** [comment]
The `name` property won't work as it will be mangled.

**Comment by Muzammil-khan710** [comment]
Hey, @theodesp. Just updated the changes you have mentioned and now it is working fine. Could you please explain me why it was working fine in `development` mode and not in `production`. 
Thank you .

**Comment by Muzammil-khan710** [comment]
Alright thanks  @theodesp you can close this issue now.
