### ISSUE TITLE
CoreVideo returns false for controls regardless of admin setting

### ISSUE THREAD

**Issue by DesignyourCode** [wpengine/wp-graphql-content-blocks#135]
When fetching the CoreVideo settings, it returns false regardless of what has been set in the admin.

I have tried to save it when set to true, and false then true and it always comes through as false.

Removing and re-adding the component also doesn't help.

**Comment by theodesp** [comment]
Thanks for the report. Will try to reproduce.

**Comment by theodesp** [comment]
Hey @DesignyourCode  I was able to reproduce. I will log a ticket and provide a fix soon. Thank you!

**Comment by theodesp** [comment]
@theodesp you could temporarily fix this by adding the following piece of code next to the following line. (although we will try to refactor the code a bit in the fix).

https://github.com/wpengine/wp-graphql-content-blocks/blob/main/includes/Blocks/Block.php#L293

```
if ( 'boolean' === $attribute_config['type'] ) {
				return ! is_null( $value );
			}
```
