### ISSUE TITLE
Expose Rendered HTML for Themes

### ISSUE THREAD

**Issue by seanaye** [wpengine/wp-graphql-content-blocks#137]
It would be great if this plugin could expose the rendered html for a Theme in addition to a Post and a Page

**Comment by theodesp** [comment]
Hey @seanaye. Thank you for the suggestion.

I think this would be probably outside the scope of this package. I will leave this issue open for a couple of days for feedback.

**Comment by justlevine** [comment]
I'm not entirely sure what `Theme` means in context of blocks. If we're referring to ~reusable blocks~ synced patterns, Site Editor templates, etc, then I 💯 thinks it makes more sense to be in `wp-graphql-content-blocks` than a separate package. 

But if we're talking about rendering a full-blown PHP template on the server and then returning the generated HTML over WPGraphQL, then that's definitely beyond the scope (and an antipattern nobody should use in production- stick with a page cache on traditional WordPress! ).

**Comment by mindctrl** [comment]
Agreed that this seems out of scope. @seanaye if you want to provide some more info about this use case or if we're misunderstanding something, please let us know.
