### ISSUE TITLE
Using the plugin as a submodule with GitHub Actions

### ISSUE THREAD

**Issue by ghost** [wpengine/wp-graphql-content-blocks#142]
I have failed to implement this plugin as a submodule in my deployment process. I use GitHub Actions to update files with a self-hosted runner that deploys my WordPress sites in production.

However, I have noticed that installing the plugin manually works perfectly. I will do this in the meantime, but it is unfortunately very cumbersome, as the plugin will get deleted everytime I push changes to my repository.

Is there a special process going on during the manual plugin install? Or am I doing something wrong?

Even when I try to install the plugin as a submodule after the manual installation (the version controlled files are the exact same as the ones being deleted and replaced), the plugin does not work properly. Accessing WpgraphQL IDE becomes impossible (the page tries to load forever).

I have been using the production ready files as well.

Thanks for your help!

**Comment by mindctrl** [comment]
@johnboylesingfield when you say you're using "production ready files", what do you mean? Can you share how you're consuming this repo exactly? I'm curious if you're running `composer install` during the process to create the composer autoload files?

**Comment by mindctrl** [comment]
@johnboylesingfield thanks for the extra info. What you're describing should be doable, but seems like something is going wrong somewhere. Are you able to get any debug.log messages from WP when it gets stuck on the loading screen?

**Comment by mindctrl** [comment]
@johnboylesingfield can you confirm the release zips for the other plugins are working correctly? There's an open issue internally for wp-graphql, wp-graphql-acf, and wp-graphql-smart-cache for fixing the zip files attached to GitHub releases here. They're unzipping without the parent folder name (with unzip in CLI. macOS creates folder name automatically, as does WP when uploaded via wp-admin), so if you're using your CI/CD pipeline to manually unzip one of those other three plugins alongside this one, that could be an issue.
