### ISSUE TITLE
Full size CoreImageAttributes.width & .height are null

### ISSUE THREAD

**Issue by ghost** [wpengine/wp-graphql-content-blocks#144]
When I try to get the width and height of an full-sized image block, WPGraphQL returns null.

However, when I manually specify a size other than the predetermined ones (thumbnail, medium, large, fullsize), the appropriate value is returned.

I'm using the last version of WPGraphQL (1.14.10) and WPGraphQL Content Blocks (1.1.3) on an fresh WordPress installation.

**Comment by theodesp** [comment]
Hey @johnboylesingfield. Thank you for the report.

This is the default behavior. The block editor uses the media details slugs for the default image sizes like medium, large or small. If you override any of the width or height it will store it as a custom style.

Here is how it works:

If you use any of the default image sizes then querying the width and height is null. Instead it uses the sizeSlug attrubute:

```
{
              "apiVersion": 2,
              "name": "core/image",
              "renderedHtml": "\n<figure class=\"wp-block-image size-full\"><img src=\"http://mysite.local/wp-content/uploads/2023/03/3F3F3F3F3F3F_3F3F3F3F3F3F3F-1.webp\" alt=\"\" class=\"wp-image-12\"/></figure>\n",
              "attributes": {
                "sizeSlug": "full",
                "width": null,
                "height": null
              }
            },
```

If you manually change the width for example it will store it in the width attribute:

```
{
              "apiVersion": 2,
              "name": "core/image",
              "renderedHtml": "\n<figure class=\"wp-block-image size-full is-resized\"><img src=\"http://mysite.local/wp-content/uploads/2023/03/3F3F3F3F3F3F_3F3F3F3F3F3F3F-1.webp\" alt=\"\" class=\"wp-image-12\" width=\"620\"/></figure>\n",
              "attributes": {
                "sizeSlug": "full",
                "width": "620",
                "height": null
              }
            },
```

We recongnize that this won't be ideal in your case. However we do have a ticket in our backlog to  expose the `mediaDetails`  of the particular image resource from the database. This way you will have access to the 


```
{
              "apiVersion": 2,
              "name": "core/image",
              "renderedHtml": "\n<figure class=\"wp-block-image size-full is-resized\"><img src=\"http://mysite.local/wp-content/uploads/2023/03/3F3F3F3F3F3F_3F3F3F3F3F3F3F-1.webp\" alt=\"\" class=\"wp-image-12\" width=\"620\"/></figure>\n",
              "attributes": {
                "sizeSlug": "full",
                "width": "620",
                "height": null
              }
            mediaItem: {
             "id":"cG9zdDoxMg==",
             "databaseId":12,
            "mediaDetails": {
              "file": "woocommerce-placeholder.png",
              "height": 1200,
              "width": 1200,
              "sizes": [
                {
                  "file": "woocommerce-placeholder-1024x1024.png",
                  "fileSize": 98202,
                  "height": "1024",
                  "mimeType": "image/png",
                  "name": "large",
                  "sourceUrl": "http://mysite.local/wp-content/uploads/woocommerce-placeholder-1024x1024.png",
                  "width": "1024"
                }
              ]
            }
          },
}
```

**Comment by theodesp** [comment]
I will post any updates here when this is supported.

**Comment by justlevine** [comment]
> This is the default behavior. The block editor uses the media details slugs for the default image sizes like medium,large or full. If you override any of the width or height it will store it as a custom style.[....]. However we do have a ticket in our backlog to expose the mediaDetails of the particular image resource from the database. This way you will have access to the full size details of the image.

This "default behavior" feels like a DX _bug_ in Gutenberg, due to common REST endpoint patterns. I love the additive approach of exposing a MediaItem connection as a workaround.

Would it also make sense to populate a null `width` and `height` on the `Model`? Getting the dimensions of a size slug on the server is a lot more performant than a db query , and would make it easier to design frontend components (e.g. using next/image with a fixed size) without needing to fall back from `sizesSlug` => `width`=> `mediaItem?.mediaDetails?.sizes( $sizeInput* )?.width`

(* Not sure offhand if an a secondary connection input can get set server-side, if not the frontend would have the extra step of filtering the `sizes` array by the `sizeSlug`).

**Comment by theodesp** [comment]
Sure we could also explore that option but we will have to make sure that we do not mess up with custom width or height.

**Comment by theodesp** [comment]
@johnboylesingfield we added the mediaDetails field in CoreImage block. It will be available in the next release version.
