### ISSUE TITLE
Custom block attributes not exposed

### ISSUE THREAD

**Issue by ivantomicic-crowdhouse** [wpengine/wp-graphql-content-blocks#149]
I might be missing something but only things I can export from custom block are className & lock. None of my attributes that I registerd in theme with registerBlockType are showing up.

**Comment by theodesp** [comment]
Hey @ivantomicic-crowdhouse would you provide a short reproduction example please? Block attributes should work as expected using a standard block.json.

**Comment by ivantomicic-crowdhouse** [comment]
Yes, you are right, I was not declaring my blocks using block.json but just using registerBlockType react script, which made it work but was not exposed in gfraphql. Using block.json fixes my issue. Thank you!
