### ISSUE TITLE
Revert CoreImageAttributes width field is of type String but it should be Float

### ISSUE THREAD

**Issue by ChrisWiegman** [wpengine/wp-graphql-content-blocks#174]
## Steps to Reproduce
Check CoreImageAttributes `width` type in GraphQLi. It is of type String.

## Issue
CoreImageAttributes.width is of type String.

## Expected Behavior
CoreImageAttributes.width should be of type Float.

## Additional Information
Note any other relevant details.

## Related ticket:
[`CoreImageAttributes.width` is type `String`, but should be a `Float` · Issue #136 · wpengine/wp-graphql-content-blocks](https://github.com/wpengine/wp-graphql-content-blocks/issues/136) 
You need to revert the following commit: [Bug: CoreImage width attribute resolve throws error. (#130) · wpengine/wp-graphql-content-blocks@28fca4a](https://github.com/wpengine/wp-graphql-content-blocks/commit/28fca4a29957a1fe827aa5e1a5ec3a1ad7bb88e4) 
However we need to document the failing unit test case and provide a workaround for this error.
The workaround is to use an alias for the `attributes` field so that GrapgQL can resolve the types without any conflicts.

![Image](https://github.com/wpengine/wp-graphql-content-blocks/assets/394675/b1423e60-3da9-45b1-8b61-c6a04c772b57)

**Comment by justlevine** [comment]
I believe i noted this in #136, but just in case the ideal fix from a schema perspective is to make all width/height attributes a `CssUnit { value: Int, unit:CssUnitTypeEnum` }` or similar, where the unit type defaults if there isn't an explicit one.

**Comment by ChrisWiegman** [comment]
@justlevine I'm sure you did. We're in the process of converting from Jira to GitHub for the teams own work and, as much as I tried to catch all the dupes in moving over work, I'm sure there are a few.

**Comment by josephfusco** [comment]
Closing this as we can continue tracking this in #136 in order to see the full context of the issue.
