### ISSUE TITLE
Getting 500 error when using this plugin with WPGraphQL

### ISSUE THREAD

**Issue by Abdullah-J01** [wpengine/wp-graphql-content-blocks#178]
I just downloaded this plugin from github (version 2.0.0)
As soon as I activate this plugin, I cannot open my graphQL IDE in wordpress dashboard
It is giving 500 error in console:
![image](https://github.com/wpengine/wp-graphql-content-blocks/assets/69471124/566428bf-a2f8-4746-aab5-e919d386742d)

Have anybody faced similar issue?
Or any help on how I can resolve this

Basically my project is using "acf_register_block" to register custom blocks and then using ACF in them, I need to expose those blocks with data in the graphQL.

**Comment by Abdullah-J01** [comment]
![image](https://github.com/wpengine/wp-graphql-content-blocks/assets/69471124/1d2ff0f7-a9c2-4f3d-8009-984e2850e8b5)

**Comment by theodesp** [comment]
Hey @Abdullah-J01 can you send me the queries are you using for this? You need to disable the plugin and check it without. 

It might be a failed GraphQL query.

**Comment by cherrygot-personal** [comment]
Maybe the debug.log entries can tell what's going wrong. Can you pass the last few lines by enabling the WP_DEBUG_LOG in wp-config.php?

**Comment by mindctrl** [comment]
@Abdullah-J01 which zip did you download exactly? Does it include the vendor folder?

**Comment by Abdullah-J01** [comment]
@theodesp  - I tried clearing out the query before activating plugin, however it did not help. I had disbaled all other plugins related to graphQL except WPGraphQL

**Comment by mindctrl** [comment]
@Abdullah-J01 that's likely the problem. If you download from the repo root or the tags view, it won't have the vendor folder. If you download the zip from the releases view, it will contain the vendor folder. https://github.com/wpengine/wp-graphql-content-blocks/releases

Note you want the zip file named wp-graphql-content-blocks.zip and not the ones with "source code" in the name.

**Comment by Abdullah-J01** [comment]
Thank you so much @mindctrl  and everyone else for such quick help. I will definitely try this and share my feedback

**Comment by mindctrl** [comment]
Thanks @Abdullah-J01. Let us know what you find. I'm going to convert this to a discussion. If you still have issues let us know and we'll investigate.

**Comment by mindctrl** [comment]
Update: forgot we don't have Discussions enabled on this repo. Going to close instead. Feel free to re-open if you're still experiencing issues.
