### ISSUE TITLE
Upload Schema Artifact workflow fails to upload schema

### ISSUE THREAD

**Issue by mindctrl** [wpengine/wp-graphql-content-blocks#197]
In #192 we attempted to fix the Schema Upload Artifact workflow by reverting [changes made previously](https://github.com/wpengine/wp-graphql-content-blocks/pull/155) which had resulted in the workflow not running. The attempted fix did not work. Source: https://github.com/wpengine/wp-graphql-content-blocks/actions/workflows/upload-schema-artifact.yml

The error is `GitHub Releases requires a tag`. It seems the context in which this runs does not have access to the tag data. cc @blakewilson for any additional context you may be able to add.

Every time we do a tagged release this workflow should run but it broke about 4 months ago and the schema linter job fails on every PR as a result. We've tried a change on this but it didn't fix it so we need to start over.

## Acceptance Criteria
- [ ] Ensure the schema linter can successfully fun on every PR and branch

## Notes
- https://github.com/wpengine/wp-graphql-content-blocks/actions/workflows/upload-schema-artifact.yml
- This will be difficult to test as it can only be tested on a release.
- Whomever works this should consider spinning up a separate repo for testing to avoid polluting this repo

**Comment by ChrisWiegman** [comment]
As the issue itself does require a full release for confirmation, I'm re-opening this ticket until such confirmation can occur.

**Comment by josephfusco** [comment]
The [schema.graphql](https://github.com/wpengine/wp-graphql-content-blocks/releases/download/v4.1.0/schema.graphql) artifact can be seen in the [latest release](https://github.com/wpengine/wp-graphql-content-blocks/releases/tag/v4.1.0). Closing this as completed.

![Image](https://github.com/user-attachments/assets/ac16c16f-9294-4905-9007-3636fbe92fd4)
