### ISSUE TITLE
Switch to new PHPCSStandards/PHP_CodeSniffer package

### ISSUE THREAD

**Issue by mindctrl** [wpengine/wp-graphql-content-blocks#199]
The `Squizlabs/PHP_CodeSniffer` package has been deprecated. It has been forked and will be maintained under a new package at `PHPCSStandards/PHP_CodeSniffer`.

Reference: [The Future of PHP_CodeSniffer · Issue #3932 · squizlabs/PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer/issues/3932) 

**Acceptance Criteria**
- [ ] Existing squizlabs package is removed and replaced with the new one.
- [ ] Existing phpcs tests continue to pass. If failures happen after upgrading, the changes needed to make it pass should happen in the same PR.

**Comment by justlevine** [comment]
@mindctrl this shouldn't be necessary: https://github.com/squizlabs/PHP_CodeSniffer/issues/3932#issuecomment-1845632122

That said, regardless there's no need to include phpcs in this package directly unless you are intentionally pinning a specific version, as it is included [upstream from vipcs](https://github.com/Automattic/VIP-Coding-Standards/blob/73d8e6df0437ca55b7bb96b5331a0d63adeadc63/composer.json#L23)
