### ISSUE TITLE
Submit plugin to WordPress.org

### ISSUE THREAD

**Issue by ChrisWiegman** [wpengine/wp-graphql-content-blocks#203]
As WP GraphQL moves to a model where they're more comfortable with extension plugins, like this one, it is time we add it to WordPress.org to make it easier for users and developers to access.

## Acceptance Criteria

- [ ] Prepare a plugin version for WordPress.org submission (may require removing update code)
- [ ] Submit to .org
- [ ] Setup CI/CD for automatic deployment when the project is accepted
- [ ] Push a new release to .org when we're ready

## Notes

- Watch the slug. We don't want to change that
- After it's on .org we'll add it's download count to our own metrics

**Comment by josephfusco** [comment]
Closing in favor of https://github.com/wpengine/faustjs/issues/1963
