### ISSUE TITLE
Latest version of Wordpress 6.5.4 returns null for various core block attributes 

### ISSUE THREAD

**Issue by rudiwebworx** [wpengine/wp-graphql-content-blocks#242]
On the latest version of wordpress 6.5.4 getting the following errors 

```
 graphQLErrors: [
    {
      message: 'Cannot query field "tagName" on type "CoreButtonAttributes".',
      extensions: [Object],
      locations: [Array]
    },
    {
      message: 'Cannot query field "type" on type "CoreButtonAttributes". Did you mean "style"?',
      extensions: [Object],
      locations: [Array]
    },
    {
      message: 'Fields "attributes" conflict because subfields "align" conflict because they return conflicting types String and String!. Use different aliases on the fields to fetch both if this was intentional.',
      extensions: [Object],
      locations: [Array]
    },

```

Seems that there have been some changes to gutenberg core blocks that require the refactoring of this plugin.

**Comment by theodesp** [comment]
Hello @rudiwebworx are you using the latest version of this plugin?

**Comment by lindseybradford** [comment]
Hi 👋 — We're also running into this upon updating from `WordPress 6.4.3` to `WordPress 6.5.5`:

<img width="819" alt="Screen Shot 2024-07-09 at 2 59 16 PM" src="https://github.com/wpengine/wp-graphql-content-blocks/assets/1048073/c3e49692-189d-4117-a29a-6bc534942dbc">
<img width="1036" alt="Screen Shot 2024-07-09 at 2 55 32 PM" src="https://github.com/wpengine/wp-graphql-content-blocks/assets/1048073/12c99bd4-4e40-484e-9d7b-f0d428de373d">

This broke all pages where these fields were queried and forced us to roll back and defer updates.

**Our environment, arrows indicating the updated environment we tried that resulted in an outage:** 
|Plugin|Version|
|--|--|
|Faust|1.3.0 -> 1.3.2|
|WordPress|5.4.3 -> 5.5.5|
|WPGraphQL|1.26.0  -> 1.27.2|

It seems that fields like `content` are now suddenly missing from Gutenberg queries, with no visible alternates.

**Comment by lindseybradford** [comment]
> Hi 👋 — We're also running into this upon updating from `WordPress 6.4.3` to `WordPress 6.5.5`:
> 
> <img alt="Screen Shot 2024-07-09 at 2 59 16 PM" width="819" src="https://private-user-images.githubusercontent.com/1048073/347146703-c3e49692-189d-4117-a29a-6bc534942dbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1NTk2NDIsIm5iZiI6MTcyMDU1OTM0MiwicGF0aCI6Ii8xMDQ4MDczLzM0NzE0NjcwMy1jM2U0OTY5Mi0xODlkLTQxMTctYTI5YS02YmM1MzQ5NDJkYmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDlUMjEwOTAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODQ2YjZjNTk3MGIxM2IwZmYzNzk2OTBlZjgxYzAyNTNjOTk3NjYwMDZiNzc2ODQ2YzFlYzUxN2Y4YzU4N2Y5OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.DRKkjqab12vOv0yq3c5eD-w99Tm0KQ_sFwdVTwcn31M"> <img alt="Screen Shot 2024-07-09 at 2 55 32 PM" width="1036" src="https://private-user-images.githubusercontent.com/1048073/347146601-12c99bd4-4e40-484e-9d7b-f0d428de373d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1NTk2NDIsIm5iZiI6MTcyMDU1OTM0MiwicGF0aCI6Ii8xMDQ4MDczLzM0NzE0NjYwMS0xMmM5OWJkNC00ZTQwLTQ4NGUtOWQ3Yi1mMGQ0MjhkZTM3M2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDlUMjEwOTAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OThmMDEyMDg1NTQ2ZjY1N2U5YWY0ZGJiZDYxMmRjYmRhN2NhNDAxYzNkMjhlMmMyNmQwNDQ3NzBjMGFmOTgxYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.a8neWs4cZFOPCgZZYYpzejorUH_VBSqxe-B9UDD6-8U">
> This broke all pages where these fields were queried and forced us to roll back and defer updates.
> 
> **Our environment, arrows indicating the updated environment we tried that resulted in an outage:**
> 
> Plugin	Version
> Faust	1.3.0 → 1.3.2
> WordPress	6.4.3 → 6.5.5
> WPGraphQL	1.26.0 → 1.27.2
> Essential fields like `content` and `caption` are now suddenly missing from Gutenberg queries, with no visible alternates in the IDE. I'm not sure if this an issue arising from [WordPress Gutenberg's](https://github.com/WordPress/gutenberg/) end or not.

I tried updating plugins and the system first—no-go. Then tried just updating the system—also a no-go. That's why I suspected the issue being that Gutenberg blocks have changed but that change isn't reflected in the content block plugin for GraphQL.

**Comment by rudiwebworx** [comment]
@theodesp yes we are using the latest with the following:

- WPGraphQL Content Blocks:  Version 4.0.1
- WPGraphQL: Version 1.27.2
- Faust.js™: Version 1.3.2
- Wordpress: 6.5.5

Errors: 
Error occurred prerendering page "/en". Read more: https://nextjs.org/docs/messages/prerender-error
ApolloError: Fields "attributes" conflict because subfields "align" conflict because they return conflicting types String and String!. Use different aliases on the fields to fetch both if this was intentional.
Fields "attributes" conflict because subfields "align" conflict because they return conflicting types String and String!. Use different aliases on the fields to fetch both if this was intentional.....

In GraphQL IDE query  "align": null

**Comment by MKlblangenois** [comment]
Hey! I run with the same issue on my side with an ACF block when I try to get `attributes.align`

![image](https://github.com/user-attachments/assets/81d383c9-e77d-4d9b-ab87-8ae53bb323df)

```ts
BlockCtaSmall.fragments = {
	blocks: gql`
		fragment BlockCtaFragment on EditorBlock {
			... on AcfBlockCta {
				anchor
				fields: blockCta {
					title
					description
					button {
						url
						title
						target
					}
				}
			}
		}
	`,
};
```


Plugin | Version
-- | --
WordPress | 6.6
WPGraphQL | 1.27.0
WPGraphQL Content Blocks | 4.0.1

**Comment by jasonbahl** [comment]
I ran into this as well. I _believe_ this is an issue related to a change in WordPress core that is getting passed  downstream.

WPGraphQL Content Blocks reads the block registry and converts it into a GraphQL Schema. If a registration of a block is changed, it can lead to changes in the Schema, and I _believe_ that is the case here. 

I want to look into it further, but I do believe it's related to a WordPress core update.

**Comment by justlevine** [comment]
Upon review -

1. Using WP 6.6, PHP 8.2, and WPGraphQL Content Blocks 4.2.0, all of the "missing fields" mentioned in this ticket are visible:

   - `CoreButtonAttributes.tagName` 
![image](https://github.com/user-attachments/assets/0cddeda1-52bb-4488-8e48-982da4a3c514)
   - `CoreButtonAttributes.type`: 
![image](https://github.com/user-attachments/assets/97d96988-e1aa-40c4-a00d-0ebee69f7832)
   - `CoreHeadingAttributes.content`: 
![image](https://github.com/user-attachments/assets/e1cd4e98-8778-4a8d-868a-cd893d70fb08)
   - `CoreQuoteAttributes.citation`: 
![image](https://github.com/user-attachments/assets/54181500-7262-4adb-b627-65f1f6298715)
   - `CorePreformattedAttributes.content`:
![image](https://github.com/user-attachments/assets/dd9ae040-34e4-403d-9813-c67a524becd7)
   - `CoreImageAttributes.caption`: 
![image](https://github.com/user-attachments/assets/a07398b7-dd08-431f-a5e5-002dfe8e7269)

2. The remaining issue is that this plugin generates types optimistically instead of deterministically, as Jason [mentioned](https://github.com/wpengine/wp-graphql-content-blocks/issues/242#issuecomment-2271596523), which can be worked around by aliasing. This causes type conflicts, potential changes between versions, and non-DX friendly types (e.g. using float for integer values or strings instead of enums).

Using determinate attribute types would both fix the type conflicts along with the possibility of an attribute getting removed/renamed from the `block.json` (which _didnt_ happen btw). 

This is being tangentially tracked in #136 (see this outdated list of type issues: https://github.com/wpengine/wp-graphql-content-blocks/issues/136#issuecomment-1685250158 )

**Comment by colinmurphy** [comment]
Currently I cannot replicate the bug in WordPress 6.5.5 with different variations of the  FaustWP, WPGraphQL and WPGraphQL Content Blocks installed or with WordPress 6.7.1 either.

**Comment by colinmurphy** [comment]
For reference here is the query I used for testing

```
query PostBySlug {
  pages(where: {id: 2}) {
    nodes {
      editorBlocks {
        ... on CoreParagraph {
          anchor
          apiVersion
          attributes {
            content
            align
          }
        }
      }
      title
      slug
    }
  }
}

```

**Screenshot**

<img width="1550" alt="image" src="https://github.com/user-attachments/assets/0bab8b03-726a-4db6-bb90-adc32bf94972" />

**Comment by colinmurphy** [comment]
Please feel free to re-open this ticket if you have any further issues. However we recommend that you update to the latest version of WPGraphQL Content Blocks (currently version 4.3.2).

Thank you for opening the ticket.
