### ISSUE TITLE
CoreVideo attributes `controls` always return true

### ISSUE THREAD

**Issue by MKlblangenois** [wpengine/wp-graphql-content-blocks#261]
When I add CoreVideo on Gutenberg and try to disable `controls` attribute, preview on Gutenberg works with no display for controls, but GraphQL return `true` in attributes
![image](https://github.com/user-attachments/assets/7bfbcccb-f307-4859-9624-426f598002e7)
![image](https://github.com/user-attachments/assets/aee15f67-1fc2-4b68-b9d2-b5f0ec7a4158)

| Plugins                  | Version |
|--------------------------|---------|
| WPGraphQL                | 1.28.0  |
| WPGraphQL Content Blocks | 4.0.1   |
| WPGraphQL for ACF        | 2.4.1   |
| WordPress        | 6.6.1   |

- [x] I can confirm that the issue appear with minimal plugin requirement (WPGraphQL and WPGraphQL Content Blocks)

**Comment by justlevine** [comment]
The reproduction is the existing `CoreVideoTest`, where [`controls` is `true`](https://github.com/wpengine/wp-graphql-content-blocks/blob/main/tests/unit/CoreVideoTest.php#L93) despite it not being included in the `post_content`.

Fixed in #284

**Comment by justlevine** [comment]
#284 was merged via #293, so I believe this can be closed as completed.

**Comment by theodesp** [comment]
Ta!
