### ISSUE TITLE
Bug: CoreTable doesn't return most data for fields

### ISSUE THREAD

**Issue by aurooba** [wpengine/wp-graphql-content-blocks#282]
Most of the data for `CoreTable` returns `null`.  The only meaningful data is returned in the `renderedHtml` field, which is not ideal.

Here's the query I used:

```
{
  pages {
    nodes {
      title
      editorBlocks(flat: false) {
        name
        clientId
        parentClientId
        ... on CoreTable {
          anchor
          apiVersion
          attributes {
            textColor
            style
            metadata
            lock
            head {
              cells {
                align
                colspan
                content
                rowspan
                tag
                scope
              }
            }
            hasFixedLayout
            gradient
            foot {
              cells {
                align
                colspan
                content
                rowspan
                scope
                tag
              }
            }
            fontSize
            fontFamily
            className
            caption
            borderColor
            body {
              cells {
                align
                colspan
                content
                rowspan
                scope
                tag
              }
            }
            backgroundColor
            anchor
            align
          }
          renderedHtml
        }
      }
    }
  }
}
```

**Comment by justlevine** [comment]
Related #242

**Comment by jasonbahl** [comment]
@aurooba was this working at one point and then stopped after an update to this plugin or WordPress core? Or was it a feature that has never worked to your knowledge?

**Comment by aurooba** [comment]
@jasonbahl I didn't try to implement `core/table` until 5 days ago, so I'm not sure if it was working before, unfortunately. But happy to go and test it against a previous version of WordPress. I'll test shortly here.

**Comment by jasonbahl** [comment]
Ok, thanks. Just trying to get an understanding of whether this is a regression or a feature that has never worked. On quick scan of the codebase, it seems to me that this has likely never worked, but I could be mistaken.

**Comment by jasonbahl** [comment]
I just tried on WordPress 6.6.2 then downgraded to WordPress 6.4 and then 6.1 and it seems to behave the same on all versions. 

Fields such as `align` on the cells return null. 🤔

**Comment by aurooba** [comment]
@jasonbahl I tested it on 6.5.5 and 6.4, and got the same result, so I suspect you're right and this hasn't worked ever!

**Comment by justlevine** [comment]
>Fields such as align on the cells always return null on all versions. 🤔

For me `align` isnt returning `null`, each cell returns the _table_ align 🫣

![image](https://github.com/user-attachments/assets/79527fbd-f65a-4d01-ae6f-c55ef553dc31)

**Comment by jasonbahl** [comment]
@justlevine interesting. possibly a difference in the data input. 

For me, I don't have align set on the table itself, just the `<th>` so I'm getting `null` instead of the value of the `data-align` on the `<th>`, which is what I would expect given that the `head.cells.align` should be sourced from `td,th data-align` (see: https://github.com/WordPress/WordPress/blob/master/wp-includes/blocks/table/block.json#L48)

Regardless, definitely getting incorrect behavior

**Comment by justlevine** [comment]
Yeah, it's seems to be a combination of using `renderedHtml` instead of a hydrated `innerHtml` and  some issues with the parsing logic.

**Comment by aurooba** [comment]
Thanks @justlevine I'm looking forward to testing it out! :D But super glad to see this getting closed and fix merged!
