### ISSUE TITLE
Example project

### ISSUE THREAD

**Issue by Messa1** [wpengine/wp-graphql-content-blocks#308]
I have a question regarding a video you posted.

[Link to the video](https://youtu.be/WvE_4-zqq5Y?si=cTVyrACkpI3BUIU2&t=497)

Is there any chance of obtaining the source code for the React frontend project? Alternatively, could you add it to the Git repository?

**Comment by josephfusco** [comment]
Hey @Messa1, you can find the [front-end block example here](https://github.com/wpengine/faustjs/tree/canary/examples/next/block-support) within the Faust.js repo.
