### ISSUE TITLE
composer installation

### ISSUE THREAD

**Issue by Messa1** [wpengine/wp-graphql-content-blocks#309]
Would be nice if you can offer an installation method through Composer.

**Comment by justlevine** [comment]
Just add this repo to composer.json's `repositories` and it should work just fine.

https://getcomposer.org/doc/04-schema.md#repositories

**Comment by Messa1** [comment]
If someone need
```

  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/wpengine/wp-graphql-content-blocks"
    }
  ],
```

```
 "require": {
    // Rest ...
    "wp-graphql/wp-graphql": "^1.29",
    "wpengine/wp-graphql-content-blocks": "dev-main"
  },
```

**Comment by justlevine** [comment]
> ```
>  "require": {
>     // Rest ...
>     "wp-graphql/wp-graphql": "^1.29",
>     "wpengine/wp-graphql-content-blocks": "dev-main"
>   },
> ```

One note, you should _not_ use `wp-graphql/wp-graphql` but rather the official distribution at `wpackagist-plugin/wp-graphql` https://wpackagist.org/

**Comment by Messa1** [comment]
https://www.wpgraphql.com/docs/quick-start#install-with-composer


![Bildschirmfoto 2024-10-07 um 15 08 05](https://github.com/user-attachments/assets/bb5b74cf-57e1-466c-827a-cd37f6bec08b)

**Comment by Messa1** [comment]
They wrote it, like I use, in there docu.
https://www.wpgraphql.com/docs/quick-start#install-with-composer
![Bildschirmfoto 2024-10-07 um 15 09 10](https://github.com/user-attachments/assets/8e15b4d7-e70d-4dd0-b04e-96b016e1408e)

**Comment by justlevine** [comment]
Be that as it may, it's a mistake in the docs 🤷‍♂️
