### ISSUE TITLE
Bug: Incorrect `WPGRAPHQL_CONTENT_BLOCKS_VERSION`

### ISSUE THREAD

**Issue by justlevine** [wpengine/wp-graphql-content-blocks#311]
Currently, the `WPGRAPHQL_CONTENT_BLOCKS_VERSION` constant is incorrectly set to `4.1.0` instead of `4.2.0`

https://github.com/wpengine/wp-graphql-content-blocks/blob/652a186c28fb613219c6465e27bf477f10eae8e9/wp-graphql-content-blocks.php#L46

I am unclear whether it is enough to trigger a new release, or if either:
- We first need to update the string manually to `4.2.0`
- The release script itself needs to be updated.

**Comment by theodesp** [comment]
Thanks @justlevine  will take a look

**Comment by thegamerjedbest45454** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by justlevine** [comment]
@theodesp @josephfusco you probably want to delete the above message and block the user ☝️

**Comment by theodesp** [comment]
@justlevine Thanks, the user has been reported on github.

**Comment by josephfusco** [comment]
This is where the versioning is happening https://github.com/wpengine/wp-graphql-content-blocks/blob/652a186c28fb613219c6465e27bf477f10eae8e9/bin/versionPlugin.js

**Comment by justlevine** [comment]
PS @josephfusco @theodesp in the 4.3.0 tag, it's now _4.2.0_ https://github.com/wpengine/wp-graphql-content-blocks/blob/6f5c0b6908d5932ac0ca5faea54edbc4b9237c5d/wp-graphql-content-blocks.php#L46

**Comment by josephfusco** [comment]
This has been resolved; thank you @justlevine 🙌🏼 
https://github.com/wpengine/wp-graphql-content-blocks/pull/314/files
