### ISSUE TITLE
Support for ACF blocks

### ISSUE THREAD

**Issue by szaleq** [wpengine/wp-graphql-content-blocks#40]
We plan to build a Faust/WordPress app with custom Gutenberg blocks created with Advanced Custom Fields. The app uses TypeScript (in strict mode) and we use [graphql-codegen](https://the-guild.dev/graphql/codegen) to generate types for GraphQL content based on the GraphQL schema exposed by WordPress backend and our frontend queries/mutations written in plain GraphQL (in `.gql` files).

## The problem
ACF exposes block fields as a single `data` attribute. In PHP there are ACF functions allowing to get values of certain fields from this `data` object. This plugin however handles object attributes by exposing them as a JSON string in GraphQL. There are two problems with this approach:
1. There are no types of ACF fields passed through GraphQL - on the frontend we only get a single `data` attribute of type `String`, so getting the real data would require manually parsing the JSON into an object and using TypeScript type guard functions with some schema validator (e.g. yup) to check if the parsed object actually contains all the fields we expect and cast it to manually defined type (this would need to be done for each custom block manually).
2. Some complex ACF fields are stored as plain arrays, e.g. repeater field called `reviews` with two nested fields: `title` and `content` and containing two items defined inside Gutenberg block would have a structure like this (simplified):
```json
{
    "reviews_0_title": "...",
    "reviews_0_content": "...",
    "reviews_1_title": "...",
    "reviews_1_content": "...",
    "_": "...there are more ACF internal items with ids pointing to field configuration etc."
}
```
While retrieving the same field with the PHP function would return an array of nested objects:
```json
{
    "reviews": [
        {
            "title": "...",
            "content": "..."
        },
        {
            "title": "...",
            "content": "..."
        }
    ],
    "_": "...other fields"
}
```
So this would require us also to rebuild a proper data structure manually in Faust (while it could be done automatically by ACF itself on the WordPress side).

## The solution
Ideally, the WPGraphQL Content Blocks plugin should handle object type attributes by exposing the fully typed data structured as it is. It would also be great to have some filters allowing to change the data structure (and its type definitions). This would allow hooking into these filters to replace the ACF `data` attribute stored inside the block with ACF-generated field values (same as the ones available in PHP with ACF functions).

Are there any plans to support nested object attributes?
Or maybe it's planned to add built-in support for ACF blocks, as it is a widely used WordPress plugin?

**Comment by theodesp** [comment]
Hey @szaleq Thank you we do have a relevant ticket in our backlog for better ACF support. We just need to refine it a bit. i will let you know for any updates.

**Comment by Kubitomakita** [comment]
Hey @theodesp do you have any ballpark timeline for such a thing? Is it a matter of a week, month, or year? It's quite a blocker for us on the project we're doing and I'd like to plan the solution for this issue so we can keep moving

**Comment by theodesp** [comment]
Hey @Kubitomakita. Thanks for asking. There are currently two issues here:

* The team is not familiar with how ACF works. We will need to get on board with ACF, how it works and what are the future changes with ACF with WPGraphQL. Maybe @jasonbahl  can provide some insights here since he is working on some new updates.
* Our current quarterly roadmap goals does not include ACF support: since we are working on improving the current block schema, and queries for Core Blocks we might only investigate the possible options for ACF.

Our roadmap after the current quarter though, does include support for a wider community plugins or libraries like ACF, so a rough estimate for this is less that a year for having a better support for ACF block field data.

**Comment by Kubitomakita** [comment]
Thanks @theodesp. If we open a PR that solves this issue for us, is there a chance to merge it quicker?

**Comment by theodesp** [comment]
Hey @Kubitomakita sure go ahead we will have to review this with @jasonbahl.

**Comment by jasonbahl** [comment]
@Kubitomakita WPGraphQL for ACF is being re-architected. 

We're in a "quiet beta" over here: https://github.com/wp-graphql/wpgraphql-acf

I plan to work on compatibility with WPGraphQL Content Blocks, but there's some other issues with WPGraphQL Content Blocks that need to be addressed before I prioritize this. 

Of course, you can register your own Types / Fields and Resolvers to accomplish this faster for your projects, but the "formal" cross-over support between the 2 plugins will likely be a month or so out I would guess.

**Comment by Kubitomakita** [comment]
Amazing @jasonbahl! We're open to helping with that development, but there are a few moving parts, and I don't want to implement something that's not mergeable :) let me know if and how we could help to speed this up

**Comment by Kubitomakita** [comment]
Hey @jasonbahl @theodesp I wanted to check on this issue. Is there anything we could do to help?

**Comment by theodesp** [comment]
Hey @Kubitomakita  we would like to start working on this once the https://github.com/wp-graphql/wpgraphql-acf is stabilised since it will serve us better in the long run.

**Comment by theodesp** [comment]
Hey @adamhavas Thanks for the suggestion I will add this soon.

**Comment by theodesp** [comment]
> However, this filtering seems to only happen at top level blocks, child blocks do not get filtered the same way.
Yes that was missed since we do not recursively traverse through the `innerBlocks` list. I will leave this open for PR's

**Comment by natedin** [comment]
Just to add to the ACF Blocks issue, the attributes > data fields serialised JSON returns the ID of images/media which would then require another call to get the url/srcSet for that image, this use to work in previous versions if wpgraphql plugin with the block field in (WP GraphQL Gutenberg ACF 0.3.0 / WP GraphQL Gutenberg 0.3.11 / WPGraphQL for Advanced Custom Fields 0.5.3) which was the accessible through the blockSlider (graphql field name for that ACF repeater field)
`fragment AcfSlider on AcfSliderBlock {
  blockSlider {
    slides {
      title
      sector
      image {
        sourceUrl
      }
      link {
        target
        title
        url
      }
    }
  }
}`

I can see that SliderBlock is still available in wpgraphql search function, which shows slides as a child node but when added to the query like above:
`query NewQuery {
  page(id: "2", idType: DATABASE_ID) {
    id
    editorBlocks {
      name
      ... on AcfSlider {
        BlockSlider {
					slides {
						title
          }
        }
      }
    }
  }
}`

Results in  "message": "Cannot query field \"BlockSlider\" on type \"AcfSlider\".",

**Comment by szaleq** [comment]
> I don't want to derail this thread but thought I'd add a finding with this current plugin regarding ACF blocks. Right now, blocks are being filtered out if their "innerHTML" is empty. ACF blocks are empty. However, this filtering seems to only happen at top level blocks, child blocks do not get filtered the same way.
> 
> Here is the file and code causing the issue:
> 
> ```
> wp-content/plugins/wp-graphql-content-blocks-main/includes/Data/ContentBlocksResolver.php
> line 60
> 
> 		// 1st Level filtering of blocks that are empty
> 		$parsed_blocks = array_filter(
> 			$parsed_blocks,
> 			function ( $parsed_block ) {
> 				// Strip empty comments and spaces
> 				return ! empty( trim( preg_replace('//Uis', '', $parsed_block['innerHTML']) ) );
> 			},
> 			ARRAY_FILTER_USE_BOTH
> 		);
> ```
> 
> Personally I'd recommend removing this filtering completely but if you need to keep it in, you can switch the 'InnerHTML' check to use 'render_block'
> 
> ```
> wp-content/plugins/wp-graphql-content-blocks-main/includes/Data/ContentBlocksResolver.php
> line 60
> 
> 		// 1st Level filtering of blocks that are empty
> 		$parsed_blocks = array_filter(
> 			$parsed_blocks,
> 			function ( $parsed_block ) {
> 				// Strip empty comments and spaces
> 				return ! empty( trim( preg_replace('//Uis', '', render_block($parsed_block)) ) );
> 			},
> 			ARRAY_FILTER_USE_BOTH
> 		);
> ```
> 
> This way, the ACF blocks will actually have their content based on the 'renderTemplate' file is provided when registering the block and has some content in it.

Actually, even `render_block` might be empty for the perfectly valid block. We are building a headless WordPress setup with the Faust.js frontend, so in WordPress, there is no content rendered by the ACF, we only need the fields to be fetched in Faust during the SSG to build static HTML pages. I'm voting to remove this check.

**Comment by justlevine** [comment]
> Actually, even render_block might be empty for the perfectly valid block. We are building a headless WordPress setup with the Faust.js frontend, so in WordPress, there is no content rendered by the ACF, we only need the fields to be fetched in Faust during the SSG to build static HTML pages. I'm voting to remove this check.

Curious @szaleq does #105 fix that particular issue?

**Comment by szaleq** [comment]
@justlevine I guess it does 😄

**Comment by jasonbahl** [comment]
👋🏻 I'm working on support for ACF Blocks over in this PR: https://github.com/wp-graphql/wpgraphql-acf/pull/81

So far, it's looking pretty promising!

**Comment by jasonbahl** [comment]
(note, my work on WPGraphQL for ACF to support ACF Blocks is currently reliant on this PR: #https://github.com/wpengine/wp-graphql-content-blocks/pull/148)

**Comment by jasonbahl** [comment]
👋🏻 yesterday's release of WPGraphQL for ACF adds support for ACF Blocks when using WPGraphQL Content Blocks v1.2.0+

Check out the release notes here: https://github.com/wp-graphql/wpgraphql-acf/releases/tag/v2.0.0-beta.5.0.0
