### ISSUE TITLE
bug: `WPGRAPHQL_CONTENT_BLOCKS_VERSION` is still `0.0.1`

### ISSUE THREAD

**Issue by justlevine** [wpengine/wp-graphql-content-blocks#58]
The `WPGRAPHQL_CONTENT_BLOCKS_VERSION` is [currently set to `0.0.`](https://github.com/wpengine/wp-graphql-content-blocks/blob/a12542ca7ae62e13ca836f8976851e86a990cf74/includes/WPGraphQLContentBlocks.php#L74), despite the fact that the current plugin version is `v0.2.0`

Not making a PR for this change, since it would require a version bump on release.

**Comment by theodesp** [comment]
Thanks we will update this once we merge the Changelog: https://github.com/wpengine/wp-graphql-content-blocks/pull/46

**Comment by blakewilson** [comment]
PR #60 will handle this.
