### ISSUE TITLE
Bug: `BlockWithSupportsAnchor` is causing `DUPLICATE_TYPE` error

### ISSUE THREAD

**Issue by justlevine** [wpengine/wp-graphql-content-blocks#98]
When querying for editor blocks with `GRAPHQL_DEBUG` enabled, I get the following `DUPLICATE_TYPE` error:
`You cannot register duplicate Types to the Schema. The Type 'BlockWithSupportsAnchor' already exists in the Schema. Make sure to give new Types a unique name.`

This is due to the fact that that `register_graphql_interface()` is being called [for every block type](https://github.com/wpengine/wp-graphql-content-blocks/blob/main/includes/Blocks/Block.php#L141). 

What should actually happen is that the `BlockWithSupportsAnchor` should be registered once in the `Registry`, and `Block::register_block_supports_field()` should only `register_interface_to_type()`. 

## Example

![image](https://github.com/wpengine/wp-graphql-content-blocks/assets/29322304/7519c162-f852-495e-a29f-0387ec696661)

**Comment by williamjulianvicary** [comment]
+1 to this, it seems related to the new registering of the NodeWith<CPTName>EditorBlocks interfaces
